on: [push]

jobs:
  render_scad_files:
    runs-on: ubuntu-latest
    container:
      image: bbassett/openscad
    name: render_scad_files
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: create stl files
        run: >
          for f in $(find . -name "*.scad"); do 
              openscad -o $(basename ${f//\.scad/.stl}) ${f};
          done
        shell: bash
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: workspace_artifacts
          path: |
            ${{ github.workspace }}/*.stl
      - name: Update and install dependencies
        run: |
          sed -i -e 's/deb http:\/\/deb.debian.org\/debian stable main/deb http:\/\/deb.debian.org\/debian buster main/' \
                 -e 's/deb http:\/\/security.debian.org\/debian-security stable\/updates main/deb http:\/\/deb.debian.org\/debian-security buster\/updates main/' \
                 -e 's/deb http:\/\/deb.debian.org\/debian stable-updates main/deb http:\/\/deb.debian.org\/debian buster-updates main/' \
              /etc/apt/sources.list
          apt-get update -q
          apt-get install -y xvfb      
      - name: create png files
        run: >
          for f in $(find . -name "*.scad"); do 
              xvfb-run -a openscad -o $(basename ${f//\.scad/.png}) ${f};
          done
        shell: bash
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: workspace_artifacts
          path: |
            ${{ github.workspace }}/*.png
      - name: Generate HTML
        run: |
          echo "<html><body><table>" > index.html
          echo "<tr>" > temp_row.html
          for img in *.png; do
            echo "<td><img src='$img' width='300'></td>" >> temp_row.html
            if [ $(($(wc -l < temp_row.html) % 3)) -eq 0 ]; then
              cat temp_row.html >> index.html
              echo "</tr><tr>" > temp_row.html
            fi
          done
          echo "</tr>" >> temp_row.html
          cat temp_row.html >> index.html
          echo "</table></body></html>" >> index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./
