on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    container:
      image: bbassett/openscad
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: create stl files
        run: >
          for f in $(find . -name "*.scad"); do 
              openscad -o $(basename ${f//\.scad/.stl}) ${f};
              openscad -o $(basename ${f//\.scad/.png}) ${f};
          done
        shell: bash
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: workspace_artifacts
          path: |
            ${{ github.workspace }}/*.png
            ${{ github.workspace }}/*.stl
