on: [push]

jobs:
  render_scad_files:
    runs-on: ubuntu-latest
    container:
      image: bbassett/openscad
    name: render_scad_files
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: create stl files
        run: >
          for f in $(find . -name "*.scad"); do 
              openscad -o $(basename ${f//\.scad/.stl}) ${f};
          done
        shell: bash

      - name: Add Debian GPG keys
        run: |
          apt-key adv --keyserver keyring.debian.org --recv-keys 0E98404D386FA1D9 6ED0E7B82643E131 F8D2585B8783D481
  
      - name: Fix or remove repositories
        run: |
          sed -i '/security.debian.org/d' /etc/apt/sources.list
  
      - name: Update and install dependencies
        run: |
          apt-get update -q
          apt-get install -y xvfb

      - name: create png files
        run: >
          for f in $(find . -name "*.scad"); do 
              xvfb-run -a openscad -o $(basename ${f//\.scad/.png}) ${f};
          done
        shell: bash
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: workspace_artifacts
          path: |
            ${{ github.workspace }}/*.png
            ${{ github.workspace }}/*.stl
