on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    container:
      image: bbassett/openscad
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: create stl files
        run: for f in $(find . -name "*.scad"); do  openscad -o $(basename ${f//\.scad/.stl}) ${f}; done
        shell: bash
