on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    container:
      image: bbassett/openscad
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test step
        run: ls -lR
